### ISSUE TITLE
Numberlink example is missing a 'no loops' constraint, and does not allow empty cells

### ISSUE THREAD

**Issue by B-Woodley** [obijywk/grilops#15]
Hello! First, thank you for creating such a great library - I've been learning Python just so I can make use of this. However, I have come across an issue with the Numberlink example, in that it doesn't implement a restriction on paths/loops that don't connect to a number. You can see this by removing the given 5s in the example puzzle; this gives enough wiggle room that the solver ends up finding multiple solutions with loops. I also think there might be an issue with there being no symbol appended to the symbol list for empty cells; _most_ Numberlinks end up using every cell, but this is not actually required - see [here](https://www.gmpuzzles.com/blog/2016/12/numberlink-thomas-snyder/) for a marvellous puzzle that makes use of empty space in its solution.

The latter issue is trivially fixed; the former seems trickier. In my own implementation of a different path-drawing genre, I have assigned each path a root with index 0 and added constraints to each other cell saying that it must have an index 1 greater than one of its neighbours on its path, thereby ensuring that cell indices increase monotonically as the path is traversed, but this seems cumbersome, so I wonder whether you might have any suggestions for a more elegant solution.

**Comment by obijywk** [comment]
Hi! Thanks for your feedback - I'm glad you're finding this library to be useful.

I agree with your assessment of these issues with the Numberlink example. I think your suggestion of numbering cells along a path to monotonically increase by 1 is a good one - and in fact, that's how the grilops loops module works (you can see how the self.__loop_order_grid is used by the LoopConstrainer).

One idea I've had in the back of my mind for a while is to break up the functionality of the loops module into both a "paths" module and a "loops" module, and then expose the ability to use these kinds of monotonic cell numbering constraints for non-looping paths in addition to looping paths. I think the Numberlink example could then be reimplemented correctly using the "paths" module.

I'll assign this to myself to try implementing for now - not sure yet when I'll get to it but hopefully sometime within the next few days.

**Comment by obijywk** [comment]
Using the new paths module, I believe this should now be fixed for the Numberlink example. There's still a bit more cleanup I want to do to fully migrate from loops to paths, but this Numberlink-specific issue can be closed.
